version: "2.3"

services:
  # Flask server
  flask:
    build:
      context: ../
      dockerfile: docker/flask/Dockerfile
    expose:
      - ${FLASK_PORT}
    volumes:
      - ../src:/src
      - ../.env:/.env
    command: bash -c "cd src && gunicorn --bind 0.0.0.0:${FLASK_PORT} 'app:create_app()' --reload"
    restart: always

  # Nginx server
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/config:/etc/nginx
      - ./nginx/log/:/var/log/nginx/
    command: /tmp/run_nginx.sh
    environment:
      - DOLLAR=$$
    env_file:
      - ./.env
    depends_on:
      - flask
    restart: always

networks:
  default:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_network
